name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: production
    if: success() && github.ref_type == 'tag'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Deploy to Greasy Fork
      #   env:
      #     GF_WEBHOOK_SECRET: ${{ secrets.GF_WEBHOOK_SECRET }}
      #   run: |
      #     payload='{
      #       "ref": "refs/tags/v2024-07-13",
      #       "before": "a4e6c9625545b2af76743283d1efb9b10504a03e",
      #       "after": "0000000000000000000000000000000000000000",
      #       "repository": {
      #         "id": 826871908,
      #         "name": "chatscroll",
      #         "full_name": "alex1yaremchuk/chatscroll",
      #         "private": false,
      #         "owner": {
      #           "name": "alex1yaremchuk",
      #           "email": "40666786+alex1yaremchuk@users.noreply.github.com"
      #         },
      #         "html_url": "https://github.com/alex1yaremchuk/chatscroll",
      #         "default_branch": "main"
      #       },
      #       "pusher": {
      #         "name": "alex1yaremchuk",
      #         "email": "40666786+alex1yaremchuk@users.noreply.github.com"
      #       },
      #       "created": false,
      #       "deleted": true,
      #       "forced": false
      #     }'
      #     response=$(curl -v -X POST -H "Content-Type: application/json" \
      #     -H "Authorization: Bearer githubsecret_here" \
      #     -d "$payload" \
      #     https://greasyfork.org/en/users/1280205-alex1yaremchuk/webhook)
      #     echo "Response code: $response"
      #     if [ "$response" -ne 200 ]; then
      #       echo "Deployment failed with response code $response"
      #       exit 1
      #     fi
