name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success() && github.ref_type == 'tag'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Greasy Fork
        # env:
        #   GF_USER: ${{ secrets.GF_USER }}
        #   GF_PASSWORD: ${{ secrets.GF_PASSWORD }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"event_type": "push"}' \
          https://greasyfork.org/en/users/1280205-alexander-yaremchuk/webhook
